apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: soma-poi-map-app-dev
  annotations:
    argocd/app-name: soma-poi-map-app-dev
    backstage.io/kubernetes-id: soma-poi-map-app
    backstage.io/kubernetes-namespace: soma
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/soma-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/soma/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/soma/deployments/soma-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/soma-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://soma-poi-map-app-soma.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/soma"
  system: workshop-system-soma
  consumesApis:
    - gateway-api-soma
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-soma
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/soma"
